# Generated by Django 4.2 on 2023-04-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_societies'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('student_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.societies')),
            ],
        ),
    ]
